import { Products } from './interfaces/products-interface'

export const products: Products = {
  '1': {
    name: 'Apple iPhone 16 | 128GB White',
    metaTitle: 'საუკეთესო ფასი │ Apple iPhone 16 მობილური ტელეფონი',
    categoryName: 'მობილური ტელეფონები',
    parentCategoryName: 'მობილური ტელეფონები',
    subCategoryName: 'Apple',
    barCode: 'ZOOM-034435',
    сategoryId: 1,
    id: 1,
    price: 2499,
    route: 'mobiluri-telefonebi/apple-iphone-16-128gb-white',
    breadcrumbs: [
      {
        id: 1,
        name: 'მობილური ტელეფონები',
        route: 'mobiluri-telefonebi',
      },
      {
        id: 1,
        name: 'Apple',
        route: 'apple-mobile-phones',
      },
    ],
    imageUrl: 'https://s3.zoommer.ge/site/ef14bec2-3156-4909-984b-444380345bc2_Thumb.png',
    images: [
      'https://s3.zoommer.ge/site/ef14bec2-3156-4909-984b-444380345bc2_Thumb.png',
      'https://s3.zoommer.ge/site/da3539d1-fb50-4c57-b081-86daa7bb29a2_Thumb.png',
      'https://s3.zoommer.ge/site/f0935fc2-6ce0-4ed7-a67c-dd9b86bb0e43_Thumb.jpeg',
    ],
    mainSpecification: [
      {
        id: 34,
        specificationName: 'ეკრანის ზომა',
        specificationMeaning: '6.1 inches',
        orderNo: 1,
      },
      {
        id: 641,
        specificationName: 'განახლების სიხშირე',
        specificationMeaning: '60 Hz',
        orderNo: 2,
      },
      {
        id: 30,
        specificationName: 'ეკრანის ტიპი',
        specificationMeaning: 'Super Retina XDR OLED',
        orderNo: 2,
      },
      {
        id: 14,
        specificationName: 'შიდა მეხსიერება',
        specificationMeaning: '128 GB',
        orderNo: 3,
      },
      {
        id: 3,
        specificationName: 'Bluetooth',
        specificationMeaning: '5.3',
        orderNo: 3,
      },
      {
        id: 13,
        specificationName: 'ოპერატიული მეხსიერება',
        specificationMeaning: '8 GB',
        orderNo: 6,
      },
    ],
    keySpecification: [
      {
        specificationName: 'ფერი',
        isColor: true,
        specificationMeaning: 'White',
        orderNo: 1,
        specificationMeaningsList: [
          {
            isColor: true,
            value: '#e6e6e6',
            isSelected: true,
            productId: 1,
            orderNo: 1,
            route: 'mobiluri-telefonebi/apple-iphone-16-128gb-white',
          },
          {
            isColor: true,
            value: '#fdecec',
            isSelected: false,
            productId: 2,
            orderNo: 19,
            route: 'mobiluri-telefonebi/apple-iphone-16-128gb-pink',
          },
          {
            isColor: true,
            value: '#0f0f0f',
            isSelected: false,
            productId: 3,
            orderNo: 35,
            route: 'mobiluri-telefonebi/apple-iphone-16-128gb-black',
          },
          {
            isColor: true,
            value: '#a3b5f7',
            isSelected: false,
            productId: 4,
            orderNo: 296,
            route: 'mobiluri-telefonebi/apple-iphone-16-128gb-ultramarine',
          },
          {
            isColor: true,
            value: '#b6d8d7',
            isSelected: false,
            productId: 5,
            orderNo: 298,
            route: 'mobiluri-telefonebi/apple-iphone-16-128gb-teal',
          },
        ],
      },
      {
        specificationName: 'შიდა მეხსიერება',
        isColor: false,
        specificationMeaning: '128 GB',
        orderNo: 5,
        specificationMeaningsList: [
          {
            isColor: false,
            value: '128 GB',
            isSelected: true,
            productId: 43988,
            orderNo: 5,
            route: 'mobiluri-telefonebi/apple-iphone-16-128gb-white',
          },
          {
            isColor: false,
            value: '256 GB',
            isSelected: false,
            productId: 43993,
            orderNo: 12,
            route: 'mobiluri-telefonebi/apple-iphone-16-256gb-white',
          },
        ],
      },
    ],
    discountAmount: 0,
    discountPercent: 0,
    discountType: 0,
    hasDiscount: false,
  },
  '2': {
    name: 'Apple iPhone 16 | 128GB Pink',
    metaTitle: 'საუკეთესო ფასი │ Apple iPhone 16 მობილური ტელეფონი',
    categoryName: 'მობილური ტელეფონები',
    parentCategoryName: 'მობილური ტელეფონები',
    subCategoryName: 'Apple',
    barCode: 'ZOOM-034435',
    сategoryId: 1,
    id: 1,
    price: 2499,
    route: 'mobiluri-telefonebi/apple-iphone-16-128gb-pink',
    breadcrumbs: [
      {
        id: 1,
        name: 'მობილური ტელეფონები',
        route: 'mobiluri-telefonebi',
      },
      {
        id: 1,
        name: 'Apple',
        route: 'apple-mobile-phones',
      },
    ],
    imageUrl: 'https://s3.zoommer.ge/site/ef14bec2-3156-4909-984b-444380345bc2_Thumb.png',
    images: [
      'https://s3.zoommer.ge/site/e0bdc0b3-8f1f-4b9c-8c87-4f76eafe8bee_Thumb.png',
      'https://s3.zoommer.ge/site/57609e9c-21ae-40be-8003-713d5c1e4667_Thumb.png',
      'https://s3.zoommer.ge/site/6c6f033e-9f14-46f4-bf12-172663ee58e4_Thumb.jpeg',
    ],
    mainSpecification: [
      {
        id: 34,
        specificationName: 'ეკრანის ზომა',
        specificationMeaning: '6.1 inches',
        orderNo: 1,
      },
      {
        id: 641,
        specificationName: 'განახლების სიხშირე',
        specificationMeaning: '60 Hz',
        orderNo: 2,
      },
      {
        id: 30,
        specificationName: 'ეკრანის ტიპი',
        specificationMeaning: 'Super Retina XDR OLED',
        orderNo: 2,
      },
      {
        id: 14,
        specificationName: 'შიდა მეხსიერება',
        specificationMeaning: '128 GB',
        orderNo: 3,
      },
      {
        id: 3,
        specificationName: 'Bluetooth',
        specificationMeaning: '5.3',
        orderNo: 3,
      },
      {
        id: 13,
        specificationName: 'ოპერატიული მეხსიერება',
        specificationMeaning: '8 GB',
        orderNo: 6,
      },
    ],
    keySpecification: [
      {
        specificationName: 'ფერი',
        isColor: true,
        specificationMeaning: 'White',
        orderNo: 1,
        specificationMeaningsList: [
          {
            isColor: true,
            value: '#e6e6e6',
            isSelected: false,
            productId: 1,
            orderNo: 1,
            route: 'mobiluri-telefonebi/apple-iphone-16-128gb-white',
          },
          {
            isColor: true,
            value: '#fdecec',
            isSelected: true,
            productId: 2,
            orderNo: 19,
            route: 'mobiluri-telefonebi/apple-iphone-16-128gb-pink',
          },
          {
            isColor: true,
            value: '#0f0f0f',
            isSelected: false,
            productId: 3,
            orderNo: 35,
            route: 'mobiluri-telefonebi/apple-iphone-16-128gb-black',
          },
          {
            isColor: true,
            value: '#a3b5f7',
            isSelected: false,
            productId: 4,
            orderNo: 296,
            route: 'mobiluri-telefonebi/apple-iphone-16-128gb-ultramarine',
          },
          {
            isColor: true,
            value: '#b6d8d7',
            isSelected: false,
            productId: 5,
            orderNo: 298,
            route: 'mobiluri-telefonebi/apple-iphone-16-128gb-teal',
          },
        ],
      },
      {
        specificationName: 'შიდა მეხსიერება',
        isColor: false,
        specificationMeaning: '128 GB',
        orderNo: 5,
        specificationMeaningsList: [
          {
            isColor: false,
            value: '128 GB',
            isSelected: true,
            productId: 43988,
            orderNo: 5,
            route: 'mobiluri-telefonebi/apple-iphone-16-128gb-white',
          },
          {
            isColor: false,
            value: '256 GB',
            isSelected: false,
            productId: 43993,
            orderNo: 12,
            route: 'mobiluri-telefonebi/apple-iphone-16-256gb-white',
          },
        ],
      },
    ],
    discountAmount: 0,
    discountPercent: 0,
    discountType: 0,
    hasDiscount: false,
  },
}
